language: php

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

env:		
  global:		
    - PHPBB_BRANCH="3.2.x"		
    - PHPBB_VERSION="3.2"		
    - PHPBB_LANGUAGE="sk"

sudo: false

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]]; then phpenv config-rm xdebug.ini; fi;
  - composer self-update
  - composer --version

install:
  - mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE
  - mkdir -p $PHPBB_VERSION/en/language
  - mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
  - mv language $PHPBB_VERSION/$PHPBB_LANGUAGE
  - mv styles $PHPBB_VERSION/$PHPBB_LANGUAGE
  - git clone "https://github.com/phpbb/phpbb.git" --branch=$PHPBB_BRANCH
  - mv phpbb/phpBB/language/en $PHPBB_VERSION/en/language
  - mv phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
  - composer install --no-interaction --prefer-source

script:
  - php vendor/bin/translation.php validate --phpbb-version=$PHPBB_VERSION $PHPBB_LANGUAGE --display-notices
